name: Build and Deploy
on:
  push: {}
  pull_request: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build variables
        id: build-variables
        run: |
          if [ ${{github.event_name}} == "pull_request" ]
          then
            echo "::set-output name=docker_push::false"
          elif [[ "${GITHUB_REF#refs/heads/}" =~ ^[0-9\.]+$ ]]
          then
            echo "::set-output name=docker_push::true"
          elif [[ "${GITHUB_REF#refs/heads/}" == "master" ]]
          then
            echo "::set-output name=docker_push::true"
          else
            echo "::set-output name=docker_push::false"
          fi
          if [ ${{github.event_name}} == "pull_request" ]
          then
            BRANCH=${GITHUB_REF#refs/pull/}
            BRANCH=${BRANCH%/merge}
            echo "::set-output name=tag::${BRANCH}"
          elif [ "${GITHUB_REF#refs/heads/}" == "master" ]
          then
            echo "::set-output name=tag::latest"
          else
            echo "::set-output name=tag::${GITHUB_REF#refs/heads/}"
          fi
      - name: Build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
          repository: parflesh/minecraft-bedrock
          tags: ${{ steps.build-variables.outputs.tag }}
          push: ${{ steps.build-variables.outputs.docker_push }}